#!/usr/bin/env python3
"""
One place that decides WHICH Excel in input/ the pipeline works on.

main.py, export_excel.py and smartbiz_export.py all used to grab
`glob("*.xlsx")[0]`. Once extract_menu.py started writing menu_items.xlsx
alongside an older sheet, that pick became a coin toss and the three stages
could each land on a different file. This makes the choice explicit and
identical everywhere.

Order of preference:
  1. $MENU_EXCEL            - an explicit path in .env or the environment
  2. input/menu_items.xlsx  - what extract_menu.py just wrote
  3. the only .xlsx in input/
  4. the newest .xlsx in input/  (and it says so out loud)
"""

import os
from pathlib import Path
from typing import List, Optional, Tuple

BASE_DIR = Path(__file__).parent.resolve()
INPUT_DIR = BASE_DIR / "input"
GENERATED_NAME = "menu_items.xlsx"


def list_input_excels(input_dir: Path = INPUT_DIR) -> List[Path]:
    """Every real .xlsx in input/ - Excel lock files (~$foo.xlsx) excluded."""
    if not input_dir.exists():
        return []
    return sorted(
        p for p in input_dir.glob("*.xlsx")
        if not p.name.startswith("~$") and p.is_file()
    )


def pick_input_excel(input_dir: Path = INPUT_DIR) -> Tuple[Optional[Path], str]:
    """
    Return (chosen path, human-readable reason). Path is None when input/ holds
    no usable sheet at all - the caller decides how loudly to complain.
    """
    override = os.getenv("MENU_EXCEL", "").strip().strip('"')
    if override:
        p = Path(override)
        if not p.is_absolute():
            p = BASE_DIR / p
        if p.exists():
            return p, "MENU_EXCEL override"
        return None, f"MENU_EXCEL points at a file that does not exist: {p}"

    candidates = list_input_excels(input_dir)
    if not candidates:
        return None, f"no .xlsx found in {input_dir}"

    generated = input_dir / GENERATED_NAME
    if generated.exists():
        return generated, "generated by extract_menu.py"

    if len(candidates) == 1:
        return candidates[0], "only sheet in input/"

    newest = max(candidates, key=lambda p: p.stat().st_mtime)
    others = ", ".join(p.name for p in candidates if p != newest)
    return newest, f"newest of {len(candidates)} sheets (ignoring: {others})"


if __name__ == "__main__":
    path, why = pick_input_excel()
    print(f"{path}  [{why}]" if path else f"X {why}")
